[build]
  # FIX: Switched to yarn to resolve npm dependency issue
  command = "yarn install && yarn build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
